apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: preflight-list-pods-global
  namespace: preflight-scanner
subjects:
- kind: ServiceAccount
  name: preflight-scanner
  namespace: preflight-scanner
