apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: preflight
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: preflight
            # you can change this to point to your image
            image: quay.io/jetstack/preflight
